version: '3'
services:
  redis-server:
    image: 'redis'
  zookeeper:
    image: 'bitnami/zookeeper:latest'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka-server:
    image: 'bitnami/kafka:latest'
    depends_on:
      - zookeeper
    environment:
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
  authentication-service:
    build: ./authentication-service
    ports:
      - "8020:8020"
  config-server:
    build: ./config-server
  eureka-server:
    build: ./eureka-server
    ports:
      - "8010:8010"
  book-service:
    build: ./book-service
    depends_on:
      - config-server
      - eureka-server
      - kafka-server
      - redis-server
    environment:
      - ENCRYPT_KEY=mysymmetrickey
  writer-service:
    build: ./writer-service
    depends_on:
      - config-server
      - eureka-server
      - kafka-server
      - redis-server
    environment:
      - ENCRYPT_KEY=mysymmetrickey
  zipkin-server:
    build: ./zipkin-server
    depends_on:
      - eureka-server
    ports:
      - "8014:8014"
  zuul-server:
    build: ./zuul-server
    depends_on:
      - zipkin-server
    ports:
      - "8080:8080"
