server:
  port: 8080
spring:
  application:
    name: zuul-service
  sleuth:
    sampler:
      probability: 1
  zipkin:
    base-url: http://localhost:8014
management:
  endpoints:
    web:
      exposure:
        include: "*"
eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8010/eureka/
zuul:
  routes:
    book-service: /book/**
  ignored-services: 'book-service'
  sensitive-headers: Cookie,Set-Cookie
#  prefix: services
