server:
  port: 8012
spring:
  cloud:
    stream:
      bindings:
        output:
          desination: bookChangeTopic
          content-type: application/json
      kafka:
        binder:
          brokers: kafka-server
  sleuth:
    sampler:
      probability: 1
  zipkin:
    base-url: http://zipkin-server:8014
