server:
  port: 8013
security:
  oauth2:
    resource:
      user-info-uri: http://authentication-service:8020/auth/user
spring:
  cloud:
    stream:
      bindings:
        input:
          destination: output
          content-type: application/json
          group: writer-group
      kafka:
        binder:
          brokers: kafka-server
  sleuth:
    sampler:
      probability: 1
  zipkin:
    base-url: http://zipkin-server:8014
redis:
  host: redis-server
  port: 6379