server:
  port: 8011
---
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/zlaval/advanced-spring-microservices/
          search-paths: config-files
          default-label: docker
        encrypt:
          enabled: false